<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { alarmActionApi, type AlarmAction } from '../../api/production';
import { formatTime } from '../../utils/format';
import { useAuthStore } from '../../stores/auth';
import PageHeader from '../../components/PageHeader.vue';
import { PAGE_COPY } from '../../navigation';
const auth=useAuthStore();const rows=ref<AlarmAction[]>([]);const total=ref(0);const page=ref(1);const size=ref(20);const loading=ref(false);const dialog=ref(false);const kind=ref<'acknowledge'|'assign'|'resolve'>('acknowledge');const current=ref<AlarmAction|null>(null);const form=reactive({sourceAlarmId:0,assignee:'',resolution:''});
async function load(){loading.value=true;try{const result=await alarmActionApi.list(page.value,size.value);rows.value=result.items;total.value=result.total;}finally{loading.value=false;}}
function open(action:'acknowledge'|'assign'|'resolve',row?:AlarmAction){kind.value=action;current.value=row??null;Object.assign(form,{sourceAlarmId:row?.sourceAlarmId??0,assignee:row?.assignee??'',resolution:row?.resolution??''});dialog.value=true;}
async function submit(){if(kind.value==='acknowledge')await alarmActionApi.acknowledge(form.sourceAlarmId);else if(current.value&&kind.value==='assign')await alarmActionApi.assign(current.value.id,current.value.version,form.assignee);else if(current.value)await alarmActionApi.resolve(current.value.id,current.value.version,form.resolution);dialog.value=false;ElMessage.success('报警处置已更新');await load();}
async function close(row:AlarmAction){await alarmActionApi.close(row.id,row.version);ElMessage.success('报警处置已关闭');await load();}onMounted(load);
</script>
<template><div class="page"><PageHeader :title="PAGE_COPY['/alarm-actions'].title" :subtitle="PAGE_COPY['/alarm-actions'].subtitle" /><div class="panel action-panel"><el-button v-if="auth.has('ALARM_ACTION_WRITE')" type="primary" @click="open('acknowledge')">确认现场报警</el-button><el-button @click="load">刷新</el-button></div><div class="panel table-panel"><el-table v-loading="loading" :data="rows"><el-table-column prop="sourceAlarmId" label="源报警编号"/><el-table-column prop="status" label="状态"/><el-table-column prop="assignee" label="处理人"/><el-table-column prop="resolution" label="处理结果" min-width="180"/><el-table-column prop="version" label="版本"/><el-table-column label="更新时间" width="180"><template #default="{row}">{{formatTime(row.updatedAt)}}</template></el-table-column><el-table-column label="操作" width="200"><template #default="{row}"><el-button v-if="auth.has('ALARM_ACTION_WRITE')&&row.status==='ACKNOWLEDGED'" link type="primary" @click="open('assign',row)">指派</el-button><el-button v-if="auth.has('ALARM_ACTION_WRITE')&&['ACKNOWLEDGED','ASSIGNED'].includes(row.status)" link type="success" @click="open('resolve',row)">处理</el-button><el-button v-if="auth.has('ALARM_ACTION_WRITE')&&row.status==='RESOLVED'" link type="warning" @click="close(row)">关闭</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" layout="total, sizes, prev, pager, next" @change="load"/></div><el-dialog v-model="dialog" :title="{acknowledge:'确认现场报警',assign:'指派处理人',resolve:'关闭异常'}[kind]" width="520"><el-form :model="form" label-width="100"><el-form-item v-if="kind==='acknowledge'" label="源报警编号"><el-input-number v-model="form.sourceAlarmId" :min="1"/></el-form-item><el-form-item v-if="kind==='assign'" label="处理人"><el-input v-model="form.assignee" maxlength="100"/></el-form-item><el-form-item v-if="kind==='resolve'" label="处理结果"><el-input v-model="form.resolution" type="textarea" :rows="5" maxlength="1000" show-word-limit/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="submit">提交</el-button></template></el-dialog></div></template>
