<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { ElMessage } from 'element-plus';
import { MASTER_TYPES, masterApi, type MasterItem, type MasterType } from '../../api/production';
import { useAuthStore } from '../../stores/auth';

const labels:Record<MasterType,string>={MATERIAL:'物料',PRODUCT:'产品',BOM:'BOM',BOM_ITEM:'BOM 明细',WORKSHOP:'车间',LINE:'产线',STATION:'工位',EQUIPMENT_BINDING:'设备绑定',OPERATION:'工序',ROUTE:'工艺路线',ROUTE_STEP:'路线步骤'};
const auth=useAuthStore();const type=ref<MasterType>('MATERIAL');const rows=ref<MasterItem[]>([]);const total=ref(0);const page=ref(1);const size=ref(20);const keyword=ref('');const loading=ref(false);const dialog=ref(false);const editingId=ref<number|null>(null);
const form=reactive({code:'',name:'',referenceId:null as number|null,secondaryReferenceId:null as number|null,sequence:null as number|null,quantity:null as number|null,attributes:'{}',enabled:true,version:0});
const filtered=computed(()=>rows.value.filter(row=>!keyword.value||`${row.code} ${row.name}`.toLowerCase().includes(keyword.value.toLowerCase())));
async function load(){loading.value=true;try{const result=await masterApi.list(type.value,page.value,size.value);rows.value=result.items;total.value=result.total;}finally{loading.value=false;}}
function open(row?:MasterItem){editingId.value=row?.id??null;Object.assign(form,{code:row?.code??'',name:row?.name??'',referenceId:row?.referenceId??null,secondaryReferenceId:row?.secondaryReferenceId??null,sequence:row?.sequence??null,quantity:row?.quantity??null,attributes:JSON.stringify(row?.attributes??{},null,2),enabled:row?.enabled??true,version:row?.version??0});dialog.value=true;}
async function save(){let attributes:Record<string,string>;try{attributes=JSON.parse(form.attributes) as Record<string,string>;}catch{ElMessage.error('属性必须是合法 JSON 对象');return;}await masterApi.save(type.value,editingId.value,{...form,attributes});dialog.value=false;ElMessage.success('主数据已保存');await load();}
watch(type,()=>{page.value=1;void load();});onMounted(load);
</script>
<template>
  <div class="page">
    <div class="panel action-panel"><el-select v-model="type" style="width:180px"><el-option v-for="item in MASTER_TYPES" :key="item" :label="labels[item]" :value="item"/></el-select><el-input v-model="keyword" placeholder="筛选编码或名称" clearable style="width:240px"/><el-button v-if="auth.has('MASTER_WRITE')" type="primary" @click="open()">新增</el-button><el-button @click="load">刷新</el-button></div>
    <div class="panel table-panel"><el-table v-loading="loading" :data="filtered"><el-table-column prop="code" label="编码"/><el-table-column prop="name" label="名称"/><el-table-column prop="referenceId" label="主引用 ID"/><el-table-column prop="secondaryReferenceId" label="次引用 ID"/><el-table-column prop="sequence" label="顺序"/><el-table-column prop="quantity" label="数量"/><el-table-column label="属性" min-width="180"><template #default="{row}">{{JSON.stringify(row.attributes)}}</template></el-table-column><el-table-column prop="version" label="版本" width="70"/><el-table-column label="操作" width="90"><template #default="{row}"><el-button v-if="auth.has('MASTER_WRITE')" link type="primary" @click="open(row)">编辑</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" layout="total, sizes, prev, pager, next" @change="load"/></div>
    <el-dialog v-model="dialog" :title="`${editingId?'编辑':'新增'}${labels[type]}`" width="680"><el-form :model="form" label-width="110"><el-form-item label="编码"><el-input v-model="form.code" maxlength="64"/></el-form-item><el-form-item label="名称"><el-input v-model="form.name" maxlength="120"/></el-form-item><el-form-item label="主引用 ID"><el-input-number v-model="form.referenceId" :min="1" clearable/></el-form-item><el-form-item label="次引用 ID"><el-input-number v-model="form.secondaryReferenceId" :min="1" clearable/></el-form-item><el-form-item label="顺序"><el-input-number v-model="form.sequence" :min="1" clearable/></el-form-item><el-form-item label="数量"><el-input-number v-model="form.quantity" :min="0" :precision="4" clearable/></el-form-item><el-form-item label="属性 JSON"><el-input v-model="form.attributes" type="textarea" :rows="6"/></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled"/></el-form-item><el-form-item label="版本"><el-input-number v-model="form.version" :min="0" disabled/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
