<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { productionApi, type ProductionTask, type WorkOrder, type WorkOrderProgress } from '../../api/production';
import { useAuthStore } from '../../stores/auth';

const auth=useAuthStore();const rows=ref<WorkOrder[]>([]);const total=ref(0);const page=ref(1);const size=ref(20);const loading=ref(false);const orderDialog=ref(false);const detailDialog=ref(false);const actionDialog=ref(false);const editingId=ref<number|null>(null);const current=ref<WorkOrder|null>(null);const tasks=ref<ProductionTask[]>([]);const progress=ref<WorkOrderProgress|null>(null);const activeTask=ref<ProductionTask|null>(null);const action=ref<'start'|'report'|'complete'>('start');
const orderForm=reactive({orderNo:'',productId:1,routeId:1,batchNo:'',plannedQuantity:1,version:0});const taskForm=reactive({barcode:'',good:0,bad:0});
async function load(){loading.value=true;try{const result=await productionApi.orders(page.value,size.value);rows.value=result.items;total.value=result.total;}finally{loading.value=false;}}
function openOrder(row?:WorkOrder){editingId.value=row?.id??null;Object.assign(orderForm,{orderNo:row?.orderNo??'',productId:row?.productId??1,routeId:row?.routeId??1,batchNo:row?.batchNo??'',plannedQuantity:row?.plannedQuantity??1,version:row?.version??0});orderDialog.value=true;}
async function saveOrder(){await productionApi.saveOrder(editingId.value,orderForm);orderDialog.value=false;ElMessage.success('工单已保存');await load();}
async function remove(row:WorkOrder){await ElMessageBox.confirm(`确认删除工单 ${row.orderNo}？`,'删除确认',{type:'warning'});await productionApi.deleteOrder(row.id,row.version);await load();}
async function release(row:WorkOrder){await productionApi.releaseOrder(row.id,row.version);ElMessage.success('工单已下达');await load();}
async function showDetail(row:WorkOrder){detailDialog.value=true;await refreshDetail(row.id);}
async function refreshDetail(id:number){const [order,taskList,orderProgress]=await Promise.all([productionApi.order(id),productionApi.tasks(id),productionApi.progress(id)]);current.value=order;tasks.value=taskList;progress.value=orderProgress;await load();}
function openAction(task:ProductionTask,kind:'start'|'report'|'complete'){activeTask.value=task;action.value=kind;Object.assign(taskForm,{barcode:'',good:0,bad:0});actionDialog.value=true;}
async function submitAction(){if(!activeTask.value||!current.value)return;const task=activeTask.value;if(action.value==='start')await productionApi.startTask(task.id,task.version,taskForm.barcode);else if(action.value==='complete')await productionApi.completeTask(task.id,task.version,taskForm.barcode);else await productionApi.reportTask(task.id,{taskVersion:task.version,orderVersion:current.value.version,good:taskForm.good,bad:taskForm.bad,barcode:taskForm.barcode});actionDialog.value=false;ElMessage.success('任务操作成功');await refreshDetail(current.value.id);}
onMounted(load);
</script>
<template>
  <div class="page">
    <div class="panel action-panel"><el-button v-if="auth.has('PRODUCTION_WRITE')" type="primary" @click="openOrder()">新建工单</el-button><el-button @click="load">刷新</el-button></div>
    <div class="panel table-panel"><el-table v-loading="loading" :data="rows"><el-table-column prop="orderNo" label="工单号"/><el-table-column prop="productId" label="产品 ID"/><el-table-column prop="routeId" label="路线 ID"/><el-table-column prop="batchNo" label="批次"/><el-table-column prop="plannedQuantity" label="计划数量"/><el-table-column prop="goodQuantity" label="合格"/><el-table-column prop="badQuantity" label="不良"/><el-table-column prop="status" label="状态"/><el-table-column prop="version" label="版本" width="70"/><el-table-column label="操作" width="250"><template #default="{row}"><el-button link type="primary" @click="showDetail(row)">详情/任务</el-button><el-button v-if="auth.has('PRODUCTION_WRITE')&&row.status==='DRAFT'" link type="primary" @click="openOrder(row)">编辑</el-button><el-button v-if="auth.has('PRODUCTION_RELEASE')&&row.status==='DRAFT'" link type="success" @click="release(row)">下达</el-button><el-button v-if="auth.has('PRODUCTION_WRITE')&&row.status==='DRAFT'" link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" layout="total, sizes, prev, pager, next" @change="load"/></div>
    <el-dialog v-model="orderDialog" :title="editingId?'编辑工单':'新建工单'" width="560"><el-form :model="orderForm" label-width="100"><el-form-item label="工单号"><el-input v-model="orderForm.orderNo" maxlength="64"/></el-form-item><el-form-item label="产品 ID"><el-input-number v-model="orderForm.productId" :min="1"/></el-form-item><el-form-item label="路线 ID"><el-input-number v-model="orderForm.routeId" :min="1"/></el-form-item><el-form-item label="批次号"><el-input v-model="orderForm.batchNo" maxlength="100"/></el-form-item><el-form-item label="计划数量"><el-input-number v-model="orderForm.plannedQuantity" :min="0.0001" :precision="4"/></el-form-item></el-form><template #footer><el-button @click="orderDialog=false">取消</el-button><el-button type="primary" @click="saveOrder">保存</el-button></template></el-dialog>
    <el-dialog v-model="detailDialog" title="工单详情与任务" width="1100"><el-descriptions v-if="current" :column="4" border><el-descriptions-item label="工单">{{current.orderNo}}</el-descriptions-item><el-descriptions-item label="状态">{{current.status}}</el-descriptions-item><el-descriptions-item label="批次">{{current.batchNo}}</el-descriptions-item><el-descriptions-item label="版本">{{current.version}}</el-descriptions-item></el-descriptions><el-progress v-if="progress" :percentage="Number(progress.completionPercent)" :format="()=>`${progress?.completedTasks}/${progress?.totalTasks} 个任务`"/><el-table :data="tasks"><el-table-column prop="sequence" label="顺序"/><el-table-column prop="operationId" label="工序 ID"/><el-table-column prop="stationId" label="工位 ID"/><el-table-column prop="plannedQuantity" label="计划"/><el-table-column prop="goodQuantity" label="合格"/><el-table-column prop="badQuantity" label="不良"/><el-table-column prop="status" label="状态"/><el-table-column prop="version" label="版本"/><el-table-column v-if="auth.has('PRODUCTION_EXECUTE')" label="操作" width="180"><template #default="{row}"><el-button v-if="row.status==='READY'" link type="success" @click="openAction(row,'start')">扫码开工</el-button><el-button v-if="row.status==='IN_PROGRESS'" link type="primary" @click="openAction(row,'report')">报工</el-button><el-button v-if="row.status==='IN_PROGRESS'" link type="warning" @click="openAction(row,'complete')">完工</el-button></template></el-table-column></el-table></el-dialog>
    <el-dialog v-model="actionDialog" :title="{start:'扫码开工',report:'报工',complete:'扫码完工'}[action]" width="500"><el-form :model="taskForm" label-width="90"><el-form-item label="条码"><el-input v-model="taskForm.barcode" maxlength="200"/></el-form-item><template v-if="action==='report'"><el-form-item label="合格数量"><el-input-number v-model="taskForm.good" :min="0" :precision="4"/></el-form-item><el-form-item label="不良数量"><el-input-number v-model="taskForm.bad" :min="0" :precision="4"/></el-form-item></template></el-form><template #footer><el-button @click="actionDialog=false">取消</el-button><el-button type="primary" @click="submitAction">提交</el-button></template></el-dialog>
  </div>
</template>
