package com.mes.system.adapter.jdbc;

import com.mes.system.domain.AuditEvent;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;

class JdbcSystemRepositoryTest {

    private EmbeddedDatabase database;
    private JdbcSystemRepository repository;

    @AfterEach
    void tearDown() {
        if (database != null) {
            database.shutdown();
        }
    }

    @BeforeEach
    void setUp() {
        database = new EmbeddedDatabaseBuilder().setName("system-" + System.nanoTime())
                .setType(EmbeddedDatabaseType.H2)
                .build();
        JdbcTemplate jdbc = new JdbcTemplate(database);
        jdbc.execute("""
                CREATE TABLE sys_user(
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  username VARCHAR(64) UNIQUE NOT NULL, display_name VARCHAR(100) NOT NULL,
                  password_hash VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL,
                  failed_attempts INT DEFAULT 0 NOT NULL, locked_until TIMESTAMP NULL)""");
        jdbc.execute("""
                CREATE TABLE sys_role(
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  code VARCHAR(64) UNIQUE NOT NULL, name VARCHAR(100) NOT NULL)""");
        jdbc.execute("""
                CREATE TABLE sys_permission(
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  code VARCHAR(100) UNIQUE NOT NULL, name VARCHAR(100) NOT NULL)""");
        jdbc.execute("CREATE TABLE sys_user_role(user_id BIGINT, role_id BIGINT)");
        jdbc.execute("CREATE TABLE sys_role_permission(role_id BIGINT, permission_id BIGINT)");
        jdbc.execute("""
                CREATE TABLE sys_menu(
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, parent_id BIGINT,
                  name VARCHAR(100), path VARCHAR(255), permission_code VARCHAR(100),
                  sort_order INT, enabled BOOLEAN)""");
        jdbc.execute("""
                CREATE TABLE sys_audit(
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor VARCHAR(64),
                  action VARCHAR(64), target_type VARCHAR(64), target_id VARCHAR(100),
                  result VARCHAR(32), correlation_id VARCHAR(80), client_ip VARCHAR(64),
                  occurred_at TIMESTAMP NOT NULL)""");
        repository = new JdbcSystemRepository(jdbc);
    }

    @Test
    void userPasswordHashStaysInsideAuthenticationEntity() {
        long id = repository.saveUser(null, "operator", "操作员", "bcrypt-hash", true);

        assertThat(repository.findUserByUsername("operator")).get()
                .satisfies(user -> {
                    assertThat(user.id()).isEqualTo(id);
                    assertThat(user.passwordHash()).isEqualTo("bcrypt-hash");
                    assertThat(user.toView().toString()).doesNotContain("bcrypt-hash");
                });
    }

    @Test
    void auditRecordsArePagedNewestFirst() {
        repository.appendAudit(new AuditEvent(null, "admin", "USER_CREATE", "USER",
                "2", "SUCCESS", "cid-1", "127.0.0.1", Instant.parse("2026-08-14T00:00:00Z")));
        repository.appendAudit(new AuditEvent(null, "admin", "ROLE_UPDATE", "ROLE",
                "1", "SUCCESS", "cid-2", "127.0.0.1", Instant.parse("2026-08-14T00:01:00Z")));

        var page = repository.findAudits(1, 1);

        assertThat(page.total()).isEqualTo(2);
        assertThat(page.items()).singleElement()
                .extracting(AuditEvent::action).isEqualTo("ROLE_UPDATE");
    }
}
